@baseGateway = http://localhost:4000


### Auth Register
POST {{baseGateway}}/auth/register
content-type: application/json

{
    "email": "test4@gmail.com",
    "password": "Test_test123456",
    "displayName": "Test User"
}


### Auth Login
POST {{baseGateway}}/auth/login
content-type: application/json

{
    "email": "test4@gmail.com",
    "password": "Test_test123456"
}
