# syntax=docker/dockerfile:1

FROM node:22-alpine AS base

#install pnpm
RUN corepack enable && corepack prepare pnpm@10.26.1 --activate

WORKDIR /app

FROM base AS deps

# Copy workspace configs
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY tsconfig.base.json tsconfig.json ./

# Copy package.json file for all needed packages
COPY packages/common/package.json ./packages/common/
COPY services/gateway-service/package.json ./services/gateway-service/

# Install dependencies
RUN pnpm install --frozen-lockfile

FROM deps AS builder

# Copy source code
COPY packages/common ./packages/common
COPY services/gateway-service ./services/gateway-service

# Build common package first
RUN pnpm --filter @chatapp/common build

# Build gateway-service
RUN pnpm --filter gateway-service build

FROM node:22-alpine AS production

# Install pnpm 
RUN corepack enable && corepack prepare pnpm@10.26.1 --activate

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nodeuser

WORKDIR /app

# Copy workspace configs
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY tsconfig.base.json ./

# Copy package.json file for all needed packages
COPY packages/common/package.json ./packages/common/
COPY services/gateway-service/package.json ./services/gateway-service/

# Install production dependencies only
RUN pnpm install --frozen-lockfile --prod

COPY --from=builder /app/packages/common/dist ./packages/common/dist
COPY --from=builder /app/services/gateway-service/dist ./services/gateway-service/dist

# Change ownership to non-root user
RUN chown -R nodeuser:nodejs /app

USER nodeuser

ENV NODE_ENV=production
ENV GATEWAY_SERVICE_PORT=4000

EXPOSE 4000

WORKDIR /app/services/gateway-service

CMD ["node", "dist/index.js"]